version: "3.8"

services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env # Pastikan DB_NAME, DB_USER, DB_PASSWORD ada di .env

  web:
    build: .
    # Jalankan migrasi otomatis & start server
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app # Menghubungkan folder lokal ke kontainer (Live Update!)
      - media_volume:/app/media
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

volumes:
  postgres_data:
  media_volume:
