# Generated by Django 5.2.11 on 2026-03-05 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_news_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='user',
            new_name='author',
        ),
    ]
