# Generated by Django 5.2.11 on 2026-02-23 13:43

import imagekit.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_agenda', models.CharField(max_length=100)),
                ('category_agenda', models.CharField(max_length=50)),
                ('description_agenda', models.TextField()),
                ('location', models.CharField(max_length=50)),
                ('date_agenda', models.DateField()),
                ('time_agenda', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_school', models.EmailField(max_length=254)),
                ('telp_school', models.CharField(max_length=20)),
                ('google_maps', models.TextField(help_text='Masukkan embed link dari Google Maps')),
                ('instagram', models.URLField(blank=True, null=True)),
                ('yotube', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_hero', models.CharField(max_length=100)),
                ('subtitle_hero', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image_hero', imagekit.models.fields.ProcessedImageField(upload_to='hero/')),
            ],
        ),
        migrations.CreateModel(
            name='Misi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('misi', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Visi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teks_visi', models.TextField()),
                ('description_image', models.CharField(max_length=50)),
                ('image_visi', imagekit.models.fields.ProcessedImageField(upload_to='visi/')),
            ],
        ),
    ]
