# Generated by Django 5.2.11 on 2026-03-11 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_agenda_status_agenda'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='yotube',
            new_name='tiktok',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='google_maps',
        ),
        migrations.AddField(
            model_name='contact',
            name='address_school',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='latitude',
            field=models.FloatField(default=0, help_text='Contoh: -6.4025'),
        ),
        migrations.AddField(
            model_name='contact',
            name='longitude',
            field=models.FloatField(default=0, help_text='Contoh: 106.7942'),
        ),
        migrations.AddField(
            model_name='contact',
            name='youtube',
            field=models.URLField(blank=True, null=True),
        ),
    ]
