# Generated by Django 5.2.11 on 2026-03-09 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_alter_gallery_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('publish', 'Publish')], default='draft', max_length=10),
        ),
    ]
